CREATE TABLE `ANIMAL` (
	  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	  `TYPE` VARCHAR(100) NOT NULL,
	  `AGE` INT(10) UNSIGNED NOT NULL,
	  `GENDER` VARCHAR(100) NOT NULL,
	  `HEIGHT` VARCHAR(100) NOT NULL,
	  PRIMARY KEY (`ID`)
	) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;